echo "Running Nick's Aliases"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias add='vi ~/.bash_aliases; new'
alias al='alias'
alias apt-get='sudo apt-get'
alias bk='t=`pwd`; \cd $OLDPWD; OLDPWD=$t'
alias cd='OLDPWD=`pwd`; cd $1'
alias d='dirs'
alias diff='colordiff'
alias gdb='cgdb'
alias h='history'
alias l='ls -CF'
alias la='ls -FCas'
alias ll='ls -l'
alias ls='ls -FCs --color=auto'
alias m='more'
alias make='colormake'
alias new='source ~/.bash_aliases'
alias po='popd'
alias pu='pushd'
alias so='source'
alias svim='sudo vim'
