echo "Running Nick's Aliases"
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias add='vi ~/.bash_aliases; new'
alias al='alias'
alias apt-get='sudo apt-get'
alias bk='t=`pwd`; \cd $OLDPWD; OLDPWD=$t'
alias cd='OLDPWD=`pwd`; cd $1'
alias coreoff='ulimit -c 0'
alias d='dirs'
alias diff='colordiff'
alias dir='dir --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep -n --color=auto'
alias h='history'
alias ls='ls -FCs --color=auto'
alias l='ls -CF'
alias la='ls -CFAs'
alias ll='ls -l'
alias m='more'
alias new='source ~/.bash_aliases'
alias po='popd'
alias pu='pushd'
alias so='source'
alias svim='sudo vim'
alias vdir='vdir --color=auto'

if [ $(hostname) == 'ng-hippocampus' ]; then
    echo "On ng-hippocampus; setting ng-hippocampus specific aliases"
    alias cadaloff='module unload cadence/allegro16.6; module unload cadence/mmsim12.1; module unload cadence/license'
    alias cadalon='module load cadence/allegro16.6'
    alias cadoff='module unload cadence/ic6.15; module unload cadence/mmsim12.1; module unload cadence/license'
    alias cadon='coreoff; module load cadence/ic6.15'
    alias cscopeoff='module unload synopsys/cosmoscope_F-2011.09; module unload synopsys/license'
    alias cscopeon='module load synopsys/cosmoscope_F-2011.09'
    alias hspiceoff='module unload synopsys/hspice_H-2013.03-SP1; module unload synopsys/license'
    alias hspiceon='module load synopsys/hspice_H-2013.03-SP1'
else
    alias make='colormake'
fi
